### ISSUE TITLE
How to append new cookie in the forwardContext.UpstreamRequest.Headers?

### ISSUE THREAD

**Issue by doggy8088** [damianh/ProxyKit#51]
There are already has some **Cookies** in the `forwardContext.UpstreamRequest.Headers`.  I'd like to add more cookies in it.  How can I do that?

**Comment by damianh** [comment]
```csharp
app.RunProxy(context =>
{
    var forwardContext = context
        .ForwardTo("http://localhost:5001")
        .AddXForwardedHeaders();
    forwardContext.UpstreamRequest.Headers.Add("Cookie", "name=value");
    return forwardContext.Send();
});
```

You could wrap this in an extension method to make it more readable. That could end up something like 

```csharp
app.RunProxy(context => context
    .ForwardTo("http://localhost:5001")
    .AddXForwardedHeaders()
    .AddCookie("name", value)
    .Send());
```

I'll leave it as an exercise to you 

**Note**: if the cookie has any security implications, you should perform checks otherwise you open yourself to client spoof attacks.

**Comment by doggy8088** [comment]
My specific question is how to "Append" a additional cookie into `forwardContext.UpstreamRequest.Headers`.   I think the `forwardContext.UpstreamRequest.Headers.Add("Cookie", "name=value");` is not a valid solution for my case.

Here is what I found:

If the original cookie is `Cooke: ga=123; abc=456`, and you run `.Add("Cookie", "name=value")` on it.  The request header's Cookie will become `Cooke: ga=123; abc=456, name=value` which is wrong Cookie format.

**Comment by damianh** [comment]
I wrote that code straight into github :) 

As you can see, you have access to the headers collection. Modify it as per your requirements.

**Comment by doggy8088** [comment]
No problem.  My issue has been solved.  I just been stucked for a while. 😄

**Comment by damianh** [comment]
Great! Share you solution here for others would be appreciated. Cheers.

**Comment by doggy8088** [comment]
Here is my final solution:

```cs
var headers = forwardContext.UpstreamRequest.Headers;

var new_cookie = "TEST=123";
var new_headers = headers.Append(new KeyValuePair<string, IEnumerable<string>>("Cookie", new string[] { new_cookie }));
var str_cookies = String.Join("; ", new_headers.Where(n => n.Key == "Cookie").Select(n => String.Join("; ", n.Value)));

headers.Remove("Cookie");
headers.Add("Cookie", str_cookies);
```

**Comment by doggy8088** [comment]
@damianh I sometimes get the error.  I have no clue why this happening.

```cs
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.Http.HttpRuleParser.GetExpressionLength(String input, Int32 startIndex, Char openChar, Char closeChar, Boolean supportsNesting, Int32& nestedCount, Int32& length)
   at System.Net.Http.Headers.ProductInfoHeaderValue.GetProductInfoLength(String input, Int32 startIndex, ProductInfoHeaderValue& parsedValue)
   at System.Net.Http.Headers.ProductInfoHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(HeaderDescriptor descriptor, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
   at System.Net.Http.Headers.HttpHeaders.GetEnumeratorCore()+MoveNext()
   at System.Linq.Enumerable.AppendPrependIterator`1.LoadFromEnumerator()
   at System.Linq.Enumerable.AppendPrepend1Iterator`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
```

**Comment by damianh** [comment]
Can you post a runnable repro to a GitHub repository OR submit a PR with a failing test? Thank you.

**Comment by doggy8088** [comment]
I reported a bug here: https://github.com/dotnet/corefx/issues/34933

I think the implementation of the `HttpRequestHeaders` or `HttpRequest` might be wrong.

Also, there is a Proposal for Cookies operation here: https://github.com/dotnet/corefx/issues/15591

**Comment by doggy8088** [comment]
@damianh I think it's user's browser sent the malformed `User-Agent` header that cause this exception.

**Comment by damianh** [comment]
Oh that's interesting. Might have to workaround / catch that. Hmm!

**Comment by doggy8088** [comment]
@damianh I can't control how user choose their buggy browser or extensions that could modify the `User-Agent` string. Even the workaround works can avoid exception, but the `.Send()` still produce exception and failed. Sigh... https://github.com/damianh/ProxyKit/issues/53 😢
