### ISSUE TITLE
Malformed User-Agent can cause IndexOutOfRangeException

### ISSUE THREAD

**Issue by doggy8088** [damianh/ProxyKit#53]
The `User-Agent` is `Mozilla/4.0 (compatible (compatible; MSIE 8.0; Windows NT 6.1; Trident/7.0)`.  This is a malformed header value from a anonymous user in my production environment.

Here is the stack trace information:

```cs
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Net.Http.HttpRuleParser.GetExpressionLength(String input, Int32 startIndex, Char openChar, Char closeChar, Boolean supportsNesting, Int32& nestedCount, Int32& length)
   at System.Net.Http.Headers.ProductInfoHeaderValue.GetProductInfoLength(String input, Int32 startIndex, ProductInfoHeaderValue& parsedValue)
   at System.Net.Http.Headers.ProductInfoHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(HeaderDescriptor descriptor, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
   at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptorsAndValuesCore()+MoveNext()
   at System.Net.Http.HttpConnection.WriteHeadersAsync(HttpHeaders headers, String cookiesFromContainer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ProxyKit.ForwardContext.Send()
```

You might need to workaround this!  

See also: https://github.com/dotnet/corefx/issues/34933 & https://github.com/damianh/ProxyKit/issues/51

**Comment by doggy8088** [comment]
What if you provide an option to skip `User-Agent` header in the [CreateProxyHttpRequest](https://github.com/damianh/ProxyKit/blob/master/src/ProxyKit/HttpContextExtensions.cs#L29-L32)?

**Comment by damianh** [comment]
Could you kindly sent a PR with a failing test for this? Don't worry about getting the test just right; something runnable for me will help me address this faster.

**Comment by damianh** [comment]
Thanks for PR - I can see the problem here too. Actually it's particularly annoying in that I can't even create a test HTTP request message to send to ProxyKit 😱

![image](https://user-images.githubusercontent.com/57436/52080891-273c5480-2599-11e9-87ff-ffd1e2692602.png)

**Comment by damianh** [comment]
I've been looking at this all evening... There are what I consider to be a couple of bugs in HttpClient related code which you have reported to CoreFX and to which I added [this comment](https://github.com/dotnet/corefx/issues/34933#issuecomment-459541074).

I'm stuck between a rock and a hard place here. ProxyKit _should_ forward headers unmangled even if they are malformed (and detecting such can be buggy too).

For now try the below as a workaround. It attempts to read the `User-Agent` and if throws, it removes it entirely from the upstream request. It's a bit nasty to be honest 😞:

```csharp
_builder.Configure(app => app.RunProxy(
    context =>
    {
        var forwardContext = context
            .ForwardTo($"http://localhost:{port}/foo/")
            .AddXForwardedHeaders();

        try
        {
            forwardContext.UpstreamRequest.Headers.TryGetValues("User-Agent", out var _);
        }
        catch (IndexOutOfRangeException)
        {
            forwardContext.UpstreamRequest.Headers.Remove("User-Agent");
        }

        return forwardContext.Send();
    }));
```

Alternatively you can replace it with something else. If this works out, I'll strongly consider adding it to the ProxyKit code.

**Comment by doggy8088** [comment]
@damianh I already apply it on my implementaion.  For your ProxyKit, I think not just `User-Agent` need this.  What if other headers also malformed?

**Comment by damianh** [comment]
I think it is futile to check every header as it has already acknowledged to be a bug. Such checks will have a performance cost. In fact, ASP.NET core will handle other malformed headers before ProxyKit is even invoked.

For now I think I am happy to handle this particular header specially and then deal with if other issue are reported later, look at it again.

**Comment by doggy8088** [comment]
No problem.  I totally agreed with you.
