### ISSUE TITLE
Performance and configuration advice

### ISSUE THREAD

**Issue by abergs** [damianh/ProxyKit#63]
I'm running in to some performance troubles while running ProxyKit in Azure (ServicePlan: S1 and P2v2).
I'm using Azure Load test with 1000 concurrent users.

What's the expected capacity for this setup? 

* Are there any important configurations in hosting to make?
* Out Of Process / In Process / Kestrel?
* AspnetCoreModuleV2 vs AspnetCoreModule?

I get these exceptions:

```csharp
System.Net.Http.HttpRequestException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full ---> System.Net.Sockets.SocketException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
```

```csharp
System.Net.Http.HttpRequestException: Only one usage of each socket address (protocol/network address/port) is normally permitted ---> System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ReverseProxy.Proxy.<ProxyWeb>b__5_1(HttpContext context) in C:\redacted\ReverseProxy.cs:line 115
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by damianh** [comment]
Hi,

ProxyKit is fundamentally just ApNetCore middleware. I don't expect it have any special hosting or configuration requirements outside of standard ASPNET core guidelines. However, would like to explore this a bit. I can somewhat imagine give enough inflight upstream HTTP requests that issues may occur.  Can you please share with me a solution in a repo that is representative of your setup, including something that indicates the behaviour of the upstream host.

**Comment by damianh** [comment]
The second stack trace is a bit strange... It doesn't appear that ProxyKit is being used there?

**Comment by abergs** [comment]
Setting up a pure repo might might be cumbersome for me, however I found that upgrading to AspnetCoreModuleV2 and inprocess gave a nice performance boost.

**Comment by damianh** [comment]
Without something reproducible, it's going to be really hard to diagnose something where we may not be looking at the same thing. Yep `AspnetCoreModuleV2` is def faster because your app is now back in `w3wp.exe` instead of being proxied to a child process. This applies to all IIS ANC apps and is not ProxyKit specific.

In the second stack trace what is `ReverseProxy.Proxy.<ProxyWeb>b__5_1(HttpContext context) in C:\redacted\ReverseProxy.cs:line 115`? I can't find reference to this anywhere on Github or elsewhere. As I am really interested in the first stack trace (port exhaustion because too many outbound requests) I want to make sure I'm looking at ProxyKit related code. It _could_ be an issue with how we are using httpclient or how httpclientfactory works or simply actually hit system limits.

As a matter of interest, can you share what kind of throughput you are getting? Can you also define the concept of a 'concurrent user' (I usually refer to requests per second)?
